import { Creature } from "../MythicalZoo";

export const creatures: Creature[] = [
  {
    id: 1,
    type: "🐉",
    name: "Smaug",
    habitat: "🌋",
    diet: "🥩",
    magicLevel: 95,
    specialAbilities: ["Flying", "Fire Breath"],
  },
  {
    id: 2,
    type: "🦄",
    name: "Twinklehoof",
    habitat: "🌳",
    diet: "🌟",
    magicLevel: 85,
    specialAbilities: ["Healing", "Rainbow Summoning"],
  },
  {
    id: 3,
    type: "🐲",
    name: "Viserion",
    habitat: "🏔️",
    diet: "🥩",
    magicLevel: 90,
    specialAbilities: ["Ice Breath", "Gliding", "Frost Aura"],
  },
  {
    id: 4,
    type: "🧜‍♀️",
    name: "Ariel",
    habitat: "🏖️",
    diet: "🌿",
    magicLevel: 80,
    specialAbilities: ["Song Enchantment", "Illusion Casting"],
  },
  {
    id: 5,
    type: "🦄",
    name: "Amalthea",
    habitat: "🌌",
    diet: "🌟",
    magicLevel: 100,
    specialAbilities: ["Healing", "Teleportation"],
  },
  {
    id: 6,
    type: "🐉",
    name: "Thaxll'ssillyia",
    habitat: "🌑",
    diet: "🔥",
    magicLevel: 85,
    specialAbilities: ["Camouflage", "Shadow Breath", "Night Vision"],
  },
  {
    id: 7,
    type: "🐉",
    name: "Ancalagon the Black",
    habitat: "🌋",
    diet: "🔥",
    magicLevel: 100,
    specialAbilities: ["Destructive power", "Immense size", "Firestorms"],
  },
  {
    id: 8,
    type: "🧜‍♀️",
    name: "Syrena",
    habitat: "🏖️",
    diet: "🐟",
    magicLevel: 75,
    specialAbilities: ["Siren's song", "Water manipulation", "Enchantments"],
  },
  {
    id: 9,
    type: "🦅",
    name: "Fawkes",
    habitat: "🏰",
    diet: "🔥",
    magicLevel: 90,
    specialAbilities: ["Rebirth from ashes", "Healing tears", "Flame teleportation"],
  },
  {
    id: 10,
    type: "👹",
    name: "Shuten-dōji",
    habitat: "⛰️",
    diet: "🍶",
    magicLevel: 85,
    specialAbilities: ["Shape-shifting", "Superhuman strength", "Fear aura"],
  },
  {
    id: 11,
    type: "🐍",
    name: "Regulus",
    habitat: "🏰",
    diet: "🐀",
    magicLevel: 80,
    specialAbilities: ["Petrifying gaze", "Deadly venom", "Silent stalking"],
  },
  {
    id: 12,
    type: "🌳",
    name: "Treebeard",
    habitat: "🌳",
    diet: "🍃",
    magicLevel: 80,
    specialAbilities: ["Immense Strength"],
  }
];
