import { Facility } from "../MythicalZoo";

export const facilities: Facility[] = [
  {
    id: 1,
    name: "Dragon's Feast",
    type: "🍴",
    description: "A restaurant serving fiery delicacies.",
    offers: ["🌶️", "🍖", "🔥"],
  },
  {
    id: 2,
    name: "Phoenix Flyer",
    type: "🎢",
    description: "A thrilling ride over the enchanted landscape.",
    offers: ["🎠", "✨"],
  },
  {
    id: 3,
    name: "Mermaid's Cove",
    type: "🏞️",
    description: "An underwater adventure where you can swim with mermaids.",
    offers: ["🧜‍♀️", "🐠"],
  },
  {
    id: 4,
    name: "Unicorn Meadow",
    type: "🏞️",
    description: "A peaceful meadow where visitors can interact with unicorns.",
    offers: ["🦄", "🌸", "🌈"],
  },
  {
    id: 5,
    name: "Shadow Labyrinth",
    type: "🏞️",
    description: "A mysterious maze filled with illusions and shadowy creatures.",
    offers: ["🌑", "👁️", "🕸️"],
  },
  {
    id: 6,
    name: "Magical Menagerie",
    type: "🛍️",
    description: "A gift shop filled with enchanted trinkets and magical souvenirs.",
    offers: ["🎁", "✨"],
  },
  {
    id: 7,
    name: "The Griffin's Nest",
    type: "🏞️",
    description: "An aerial show featuring majestic griffins.",
    offers: ["🦅", "🌥️", "🎭"],
  },
  {
    id: 8,
    name: "Oni's Dojo",
    type: "🎭",
    description: "A martial arts arena where you can learn from the legendary Oni.",
    offers: ["👹", "⚔️", "🥋"],
  },
  {
    id: 9,
    name: "Frostbite Cafe",
    type: "🍴",
    description: "A chilly cafe serving icy treats and magical frost drinks.",
    offers: ["🍨", "🧊", "❄️"],
  },
  {
    id: 10,
    name: "Basilisk's Gaze",
    type: "🎥",
    description: "A 4D experience of the basilisk's underground lair.",
    offers: ["🐍", "👁️", "🎬"],
  },
  {
    id: 11,
    name: "The Dragon Coaster",
    type: "🎢",
    description: "A heart-pounding roller coaster that takes you through a dragon's lair.",
    offers: ["🐉", "🔥", "🎠"],
  },
  {
    id: 12,
    name: "Cinematic Spells",
    type: "🎥",
    description: "A 4D magical movie experience that immerses you in wizarding duels and enchanted worlds.",
    offers: ["✨", "🎬"],
  },
  {
    id: 13,
    name: "The Enchanted Theater",
    type: "🎭",
    description: "A live performance showcasing magical creatures and epic battles.",
    offers: ["🦄", "🐉", "🎭"],
  },
];
