import { Visitor } from "../MythicalZoo";

export const visitors: Visitor[] = [
  {
    id: 1,
    name: "Merlin",
    type: "🧙",
    ticketType: "👑 VIP",
    favoriteCreatures: [7, 9],
  },
  {
    id: 2,
    name: "Elminster",
    type: "🧙",
    ticketType: "👑 VIP",
    favoriteCreatures: [1, 11],
  },
  {
    id: 3,
    name: "Diana Prince",
    type: "🦸",
    ticketType: "🎫 Standard",
    favoriteCreatures: [4, 12],
  },
  {
    id: 4,
    name: "Percy Jackson",
    type: "🧙",
    ticketType: "🎫 Standard",
    favoriteCreatures: [2],
  },
  {
    id: 5,
    name: "Daenerys Targaryen",
    type: "👸",
    ticketType: "👑 VIP",
    favoriteCreatures: [3],
  },
  {
    id: 6,
    name: "Link",
    type: "🦸",
    ticketType: "🎫 Standard",
    favoriteCreatures: [5],
  },
  {
    id: 7,
    name: "Legolas",
    type: "🧝",
    ticketType: "🎫 Standard",
    favoriteCreatures: [1],
  },
  {
    id: 8,
    name: "Harry Potter",
    type: "🧙",
    ticketType: "🎫 Standard",
    favoriteCreatures: [9],
  },
  {
    id: 9,
    name: "Geralt of Rivia",
    type: "🦸",
    ticketType: "🎫 Standard",
    favoriteCreatures: [10],
  },
  {
    id: 10,
    name: "Ciri",
    type: "🦸",
    ticketType: "👑 VIP",
    favoriteCreatures: [5, 4],
  },
  {
    id: 11,
    name: "Caroline",
    type: "👸🏾",
    ticketType: "👑 VIP",
    favoriteCreatures: [5],
  },
];
